title: AnnaWisdom Blog
SEOTitle: AnnaWisdom的博客 | AnnaWisdom Blog
header-img: img/bg-0327.jpg
description: "Be the change you want to see in the world."
url: "https://annawisdom.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Just have a little faith!"
sidebar-avatar: /img/avatar_g.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

plugins: [jekyll-paginate]

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

